### ISSUE TITLE
Backport bundling to github for delayed_job to fix Rails 5.1 issues

### ISSUE THREAD

**Issue by jondkinney** [headwayio/suspenders#10]
```ruby
gem 'delayed_job_active_record', github: 'collectiveidea/delayed_job_active_record', branch: 'gogovan-rails-5-1'

gem 'delayed_job', github: 'dsander/delayed_job', branch: 'rails51'
```

**Comment by jondkinney** [comment]
We might want to just stop using delayed_job all together and manually pull in sidekiq when necessary (or possibly by default).

**Comment by noahsettersten** [comment]
I'm closing this in favor of #22 for integrating Sidekiq as the default job processor. That will be a much nicer and more robust default across the board.
