### ISSUE TITLE
Authentication Fix

### ISSUE THREAD

**Issue by GeekOnCoffee** [headwayio/suspenders#30]
app/controllers/application_controller.rb
# TODO: (2017-06-21) jon => port this unless: -> to voyage. This is why it redirects to the sign all the time before displaying the welcome. 

`acts_as_token_authentication_handler_for User, unless: -> { is_a?(HighVoltage::PagesController) }`

**Comment by noahsettersten** [comment]
When we integrate the `tiddle` gem for Voyage, this will replace this handler as well as a few other logic flows in the app. We've moved all of our APIs to this gem instead since it's offers more robust handling of authentication while still using basic token auth.

Closing this in favor of #28

**Comment by GeekOnCoffee** [comment]
👍
