### ISSUE TITLE
Generate Tmux Config

### ISSUE THREAD

**Issue by GeekOnCoffee** [headwayio/suspenders#42]
Not sure if this fits here, but it'd be nice to have templates for these included.

**Comment by noahsettersten** [comment]
There doesn't appear to be any way to store the tmuxinator config within a project's folder/repo. There are a couple outstanding issues and PRs around this feature, but none are finished or merged as of yet.

Tmuxinator does have the ability to pass variables into your sessions: https://github.com/tmuxinator/tmuxinator#erb. It may be possible for us to create a standard 'Rails' tmux setup and then pass in the root folder as a variable from there.

Another option would be to create a tmuxinator YML file in the project and then symlink that into `~/.tmuxinator`

**Comment by noahsettersten** [comment]
https://stackoverflow.com/questions/20901252/tmuxinator-specify-custom-project-config-file
https://github.com/tmuxinator/tmuxinator/pull/91

**Comment by GeekOnCoffee** [comment]
Even handling this like we handle .env.sample where it generated it but you had to copy it yourself wouldn't be bad, but probably not worth it.
