### ISSUE TITLE
Data no-turbolinks on admin link for administrate

### ISSUE THREAD

**Issue by jondkinney** [headwayio/suspenders#71]
Otherwise the JS and styles get carried over

**Comment by noahsettersten** [comment]
I believe this is in place already: https://github.com/headwayio/voyage/blob/master/lib/voyage/templates/navigation.html.erb#L10

```ruby
 <%%= active_link_to 'Admin', admin_users_path, data: { no_turbolink: true } %>
```

We'll have to review if it isn't working as expected.

**Comment by noahsettersten** [comment]
I've updated this to the latest Turbolinks 5 syntax as provided by @GeekOnCoffee and it will be in a PR shortly.
