### ISSUE TITLE
Default welcome view is ERB should be Slim

### ISSUE THREAD

**Issue by jason-headway** [headwayio/suspenders#77]

**Comment by jondkinney** [comment]
@jason-headway IIRC, it wasn't possible to embed the readme as markdown unless we rendered it as erb. But not sure how useful that embed was, or if we're even still doing it.

**Comment by noahsettersten** [comment]
We're still embedding the README in the initial page, but it seems like that's one of the first things to be customized on an app generation anyway. Mind if I just remove the markdown include? We can remove the Redcarpet gem as well then.

**Comment by jondkinney** [comment]
@noahsettersten yep, thanks! Get 'er out of there!
