### ISSUE TITLE
Add `if` modifier to allow conditionally disabling token authentication

### ISSUE THREAD

**Issue by noahsettersten** [headwayio/suspenders#8]
Disabling all authorization via cancan, etc. still causes API routes to require a valid token for authentication. This can be managed by adding this `if` modifier on the end of the token handler statement in `application_controller.rb`:
```
acts_as_token_authentication_handler_for User, if: :token_authenticatable?
```

Later in `application_controller.rb`, define this method:
```
def token_authenticatable?
    true
end
```

Then in those controllers / actions that need to be public, override this method and pass `false` to bypass the token authentication.

**Comment by jondkinney** [comment]
Thanks for that @noahsettersten! I'd like to see how deep into devise this goes and whether or not there is a `skip_before_action` way to allow publicly accessible endpoints to exist. If not, this is a good workaround/solution.

**Comment by noahsettersten** [comment]
Adding tiddle to voyage actually makes the need for this obsolete. I'll close this out as an old request.
